---
# ansible related variables
ansible_python_interpreter: /usr/bin/python3

# general pg_cluster variables
## default floating ip is .100
pg_floating_ip:
  "{{ hostvars[groups[pg_cluster_group][0]].ansible_default_ipv4.network
  | ipmath(100) }}"
