---
dependency:
  name: galaxy
driver:
  name: docker
  # pull: false
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: pg-master
    hostname: pg-master
    image: geerlingguy/docker-${DISTRO:-debian10}-ansible
    networks:
      - name: molecule_pg_network
      - name: molecule_pg_network_replication
    purge_networks: true
    privileged: true
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    capabilities:
      - SYS_ADMIN
    published_ports:
      - "127.1.1.2:5432:5432"
    command: '/lib/systemd/systemd'
  - name: pg-backup-01
    hostname: pg-backup-01
    image: geerlingguy/docker-${DISTRO:-debian10}-ansible
    networks:
      - name: molecule_pg_network
      - name: molecule_pg_network_replication
    purge_networks: true
    privileged: true
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    capabilities:
      - SYS_ADMIN
    published_ports:
      - "127.1.1.3:5432:5432"
    command: '/lib/systemd/systemd'
  - name: pg-backup-02
    hostname: pg-backup-02
    image: geerlingguy/docker-${DISTRO:-debian10}-ansible
    networks:
      - name: molecule_pg_network
      - name: molecule_pg_network_replication
    purge_networks: true
    privileged: true
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    capabilities:
      - SYS_ADMIN
    published_ports:
      - "127.1.1.4:5432:5432"
    command: '/lib/systemd/systemd'
provisioner:
  name: ansible
  # log: true
  inventory:
    # use host ini file for preserving order in group pg_cluster
    links:
      hosts: hosts
